export const doljabiOptions = [
  {
    id: 'money',
    label: '돈',
    detail: '부자, 재물운, 사업가',
    image: '/돈.png',
    x: '-270px',
    y: '-8px',
    rotation: '-7deg',
  },
  {
    id: 'mouse',
    label: '마우스',
    detail: '개발자, IT인재, 디자이너, 컴퓨터 잘하는 사람',
    image: '/마우스.png',
    x: '-90px',
    y: '-12px',
    rotation: '5deg',
  },
  {
    id: 'microphone',
    label: '마이크',
    detail: '연예인, 방송인, 가수, 발표 잘하는 사람',
    image: '/마이크.png',
    x: '90px',
    y: '-7px',
    rotation: '-5deg',
  },
  {
    id: 'thread',
    label: '명주실',
    detail: '무병장수, 오래 건강하게 살기',
    image: '/명주실.png',
    x: '270px',
    y: '-12px',
    rotation: '6deg',
  },
  {
    id: 'airplane',
    label: '비행기',
    detail: '파일럿, 승무원, 여행가, 세계로 뻗어나가는 사람',
    image: '/비행기.png',
    x: '-270px',
    y: '118px',
    rotation: '-8deg',
  },
  {
    id: 'stethoscope',
    label: '청진기',
    detail: '의사, 의료인, 건강을 돌보는 사람',
    image: '/청진기.png',
    x: '-90px',
    y: '118px',
    rotation: '6deg',
  },
  {
    id: 'camera',
    label: '카메라',
    detail: '사진작가, 영상감독, 크리에이터, 예술가',
    image: '/카메라.png',
    x: '90px',
    y: '118px',
    rotation: '-7deg',
  },
  {
    id: 'gavel',
    label: '판사봉',
    detail: '판사, 변호사, 법조인, 공정한 사람',
    image: '/판사봉.png',
    x: '270px',
    y: '118px',
    rotation: '9deg',
  },
]

export function optionLabel(id) {
  return doljabiOptions.find((option) => option.id === id)?.label ?? id
}
