export const doljabiOptions = [
  {
    id: 'judge_gavel',
    label: '판사봉',
    detail: '법조인, 정의, 판단력',
    image: '/판사봉.png',
    x: '-270px',
    y: '-8px',
    rotation: '-7deg',
  },
  {
    id: 'money',
    label: '지폐',
    detail: '재물운, 경제력, 사업가',
    image: '/돈.png',
    x: '-90px',
    y: '-12px',
    rotation: '5deg',
  },
  {
    id: 'silk_thread',
    label: '명주실',
    detail: '무병장수, 건강, 오래 사는 복',
    image: '/명주실.png',
    x: '90px',
    y: '-7px',
    rotation: '-5deg',
  },
  {
    id: 'stethoscope',
    label: '청진기',
    detail: '의사, 의료인, 생명을 돌보는 사람',
    image: '/청진기.png',
    x: '270px',
    y: '-12px',
    rotation: '6deg',
  },
  {
    id: 'microphone',
    label: '마이크',
    detail: '방송인, 연예인, 말솜씨, 무대 재능',
    image: '/마이크.png',
    x: '-270px',
    y: '118px',
    rotation: '-8deg',
  },
  {
    id: 'mapa',
    label: '마패',
    detail: '공직, 명예, 책임감, 리더십',
    image: '/마패.svg',
    x: '-90px',
    y: '118px',
    rotation: '6deg',
  },
  {
    id: 'colored_pencil',
    label: '색연필',
    detail: '예체능, 창의력, 미술적 재능',
    image: '/색연필.svg',
    x: '90px',
    y: '118px',
    rotation: '-7deg',
  },
  {
    id: 'brush',
    label: '붓',
    detail: '글작가, 문인, 언어 능력, 학문적 재능',
    image: '/붓.svg',
    x: '270px',
    y: '118px',
    rotation: '9deg',
  },
]

export function optionLabel(id) {
  return doljabiOptions.find((option) => option.id === id)?.label ?? id
}
